### ISSUE TITLE
How to plant wither seeds?

### ISSUE THREAD

**Issue by KnightCa** [Unixkitty/finallyfarmabledyes#3]
I've tried on Soul Sand, Soul Soil, Dirt, Rich Soil.. with Torchlight and without.. in Overworld and Nether.

What are the requirements?

**Comment by Unixkitty** [comment]
Have you tried... regular farmland? Just like all the other seeds?

**Comment by KnightCa** [comment]
Yep, worked in the overworld with regular farmland. Thanks mates. Feel silly.
